In [32]:
import pandas as pd
import numpy as np
df = pd.read_csv('E:/Academics/4_1/CSE 4112_MLL/Lab_1/diabetes.csv')
df.head(10)
inputs = df.drop(['Pregnancies','SkinThickness','BloodPressure','BMI','DiabetesPedigreeFunction','Age','Outcome'],axis='columns')
inputs
data= df.drop(['Pregnancies','SkinThickness','BloodPressure','BMI','DiabetesPedigreeFunction','Age'],axis='columns')
data


Glucose  Insulin  Outcome
0        148        0        1
1         85        0        0
2        183        0        1
3         89       94        0
4        137      168        1
..       ...      ...      ...
763      101      180        0
764      122        0        0
765      121      112        0
766      126        0        1
767       93        0        0

[768 rows x 3 columns]

In [33]:
random_v = data.sample(n=10)
random_variable = random_v.to_numpy()
random_variable

array([[136,   0,   1],
       [147,   0,   0],
       [121,   0,   1],
       [121,   0,   0],
       [114, 285,   0],
       [118, 230,   1],
       [125,   0,   0],
       [ 71,   0,   0],
       [103,   0,   0],
       [109, 182,   0]], dtype=int64)

In [34]:
import numpy as np
#glucose = inputs['Glucose']
glucose = pd.Series(inputs['Glucose'])
array_g = np.array(glucose)
array_g

array([148,  85, 183,  89, 137, 116,  78, 115, 197, 125, 110, 168, 139,
       189, 166, 100, 118, 107, 103, 115, 126,  99, 196, 119, 143, 125,
       147,  97, 145, 117, 109, 158,  88,  92, 122, 103, 138, 102,  90,
       111, 180, 133, 106, 171, 159, 180, 146,  71, 103, 105, 103, 101,
        88, 176, 150,  73, 187, 100, 146, 105,  84, 133,  44, 141, 114,
        99, 109, 109,  95, 146, 100, 139, 126, 129,  79,   0,  62,  95,
       131, 112, 113,  74,  83, 101, 137, 110, 106, 100, 136, 107,  80,
       123,  81, 134, 142, 144,  92,  71,  93, 122, 163, 151, 125,  81,
        85, 126,  96, 144,  83,  95, 171, 155,  89,  76, 160, 146, 124,
        78,  97,  99, 162, 111, 107, 132, 113,  88, 120, 118, 117, 105,
       173, 122, 170,  84,  96, 125, 100,  93, 129, 105, 128, 106, 108,
       108, 154, 102,  57, 106, 147,  90, 136, 114, 156, 153, 188, 152,
        99, 109,  88, 163, 151, 102, 114, 100, 131, 104, 148, 120, 110,
       111, 102, 134,  87,  79,  75, 179,  85, 129, 143, 130,  8

In [35]:
#insulin = inputs['Insulin']
Insulin = pd.Series(inputs['Insulin'])
array_i = np.array(Insulin)
array_i

array([  0,   0,   0,  94, 168,   0,  88,   0, 543,   0,   0,   0,   0,
       846, 175,   0, 230,   0,  83,  96, 235,   0,   0,   0, 146, 115,
         0, 140, 110,   0,   0, 245,  54,   0,   0, 192,   0,   0,   0,
       207,  70,   0,   0, 240,   0,   0,   0,   0,   0,   0,  82,  36,
        23, 300, 342,   0, 304, 110,   0, 142,   0,   0,   0, 128,   0,
         0,   0,   0,  38, 100,  90, 140,   0, 270,   0,   0,   0,   0,
         0,   0,   0,   0,  71,   0,   0, 125,   0,  71, 110,   0,   0,
       176,  48,   0,  64, 228,   0,  76,  64, 220,   0,   0,   0,  40,
         0, 152,   0, 140,  18,  36, 135, 495,  37,   0, 175,   0,   0,
         0,   0,  51, 100,   0, 100,   0,   0,  99, 135,  94, 145,   0,
       168,   0, 225,   0,  49, 140,  50,  92,   0, 325,   0,   0,  63,
         0, 284,   0,   0, 119,   0,   0, 204,   0, 155, 485,   0,   0,
        94, 135,  53, 114,   0, 105, 285,   0,   0, 156,   0,   0,   0,
        78,   0, 130,   0,  48,  55, 130,   0, 130,   0,   0,   

In [36]:
#target = df['Outcome']
target = pd.Series(df['Outcome'])
array_t = np.array(target)
array_t

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [37]:
distance = []
outcome1 = []
for i in range(array_g.size):
    result= ((((array_g[i] - 120 )**2) + ((array_i[i]-100)**2) )**0.5)
    distance.append(result)
    outcome1.append(array_t[i])
distance

[103.84603988597736,
 105.94810050208545,
 118.1905241548577,
 31.575306807693888,
 70.09279563550022,
 100.07996802557443,
 43.68065933568311,
 100.12492197250393,
 449.64207988132074,
 100.12492197250393,
 100.4987562112089,
 110.92339699089638,
 101.78899744078434,
 749.1842230052632,
 87.98295289429652,
 101.9803902718557,
 130.01538370516005,
 100.84145972763385,
 24.041630560342615,
 6.4031242374328485,
 135.1332675546625,
 102.18121158021175,
 125.60254774486066,
 100.00499987500625,
 51.42956348249516,
 15.811388300841896,
 103.58088626768937,
 46.14108798023731,
 26.92582403567252,
 100.04498987955368,
 100.60318086422517,
 149.8966310495336,
 56.0357029044876,
 103.84603988597736,
 100.0199980003999,
 93.55746896961247,
 101.6070863670443,
 101.6070863670443,
 104.4030650891055,
 107.37783756436893,
 67.08203932499369,
 100.84145972763385,
 100.9752444909147,
 149.0,
 107.33592129385204,
 116.61903789690601,
 103.32473082471591,
 111.35977729862789,
 101.43470806385751,
 101.

In [38]:
outcome1

[1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,


In [39]:
import numpy as np
result = np.column_stack((distance, outcome1))
result

array([[103.84603989,   1.        ],
       [105.9481005 ,   0.        ],
       [118.19052415,   1.        ],
       ...,
       [ 12.04159458,   0.        ],
       [100.17983829,   1.        ],
       [103.58088627,   0.        ]])

In [40]:
sorted_li = sorted(result, key=lambda result:result[0])
print(sorted_li)

[array([5., 0.]), array([5.09901951, 0.        ]), array([5.83095189, 0.        ]), array([6.32455532, 0.        ]), array([6.32455532, 0.        ]), array([6.40312424, 1.        ]), array([6.40312424, 0.        ]), array([6.40312424, 0.        ]), array([6.70820393, 0.        ]), array([6.70820393, 0.        ]), array([8.06225775, 0.        ]), array([10.,  0.]), array([10.,  0.]), array([10.,  0.]), array([11.04536102,  1.        ]), array([11.18033989,  0.        ]), array([11.18033989,  0.        ]), array([11.18033989,  0.        ]), array([11.66190379,  0.        ]), array([12.04159458,  0.        ]), array([12.80624847,  1.        ]), array([13.,  0.]), array([13.60147051,  0.        ]), array([15.8113883,  1.       ]), array([16.15549442,  0.        ]), array([16.55294536,  0.        ]), array([17.49285568,  1.        ]), array([17.80449381,  1.        ]), array([18.68154169,  0.        ]), array([18.68154169,  0.        ]), array([18.86796226,  1.        ]), array([18.97366596

In [41]:
output = []
for i in range(5):
    output.append(sorted_li[i])
output[0][1]

0.0

In [42]:
z = 0
o= 0
for i in range(len(output)):
    if(output[i][1]==0):
        z = z+1
    else:
        o = o + 1
if z>o:
    print("Not:",z)
else:
    print("Yes:",o)

Not: 5


In [43]:
distance = []
outcome1 = []
result_z = []
result_o = []

for x in range(10):
  
    for i in range(array_g.size):
        result= ((((array_g[i] - random_variable[x][0] )**2) + ((array_i[i] - random_variable[x][1])**2) )**0.5)
        distance.append(result)
        outcome1.append(array_t[i])
   
    result = np.column_stack((distance, outcome1))
    sorted_li = sorted(result, key=lambda result:result[0])
    output = []
    for i in range(6):
        output.append(sorted_li[i])
    
    zero = 0
    one= 0
    for i in range(len(output)):
        if(output[i][1]==0):
            zero = zero+1
        else:
            one = one + 1
    if zero>one:
        result_z.append(0)
        print("Not:",zero)
    else:
        result_z.append(1)
        print("Yes:",one)
    

Yes: 3
Not: 4
Not: 4
Not: 4
Not: 4
Not: 4
Not: 4
Not: 4
Not: 4
Not: 4


In [44]:
result_z

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [45]:
total =0
yes=0
no=0
for i in range(10):
    total +=1
    if(result_z[i] == random_variable[i][2]):
        yes +=1
    else:
        no+=1
        
    
    

In [46]:
accuracy = yes/total
print(accuracy *100)


80.0
